apiVersion: v1
kind: Service
metadata:
  name: task-manager-service-nodeport
spec:
  selector:
    app: task-manager
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000